version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/schedule-db
    depends_on:
      - mongo
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    ports:
      - '8080:80'
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge